---
- name: Install/Upgrade DB2 Fix pack special build on db2 server
  gather_facts: true
  hosts: IGITest
  vars:
    new_db2_path: "/opt/ibm/db2/V11.5.9_SP"
    base_db2_path: "/opt/ibm/db2/V11.5.9"
    temp_dir: "/tmp"
    db2_binary_location: "/opt/ibm/db2"
  vars_prompt:
    - name: db2_bin_temp
      prompt: "Enter the fix pack  binary software path location:"
  roles:
    - db2-fixpack
