---
- name: Install  update and configure Java on db2 server
  gather_facts: true
  hosts:  all
  become: yes
  become_method: sudo
  vars:
    db2_path: "/opt/ibm/db2/V11.5.9_SP"
  vars_prompt:
    - name: jdk_binary_location
      prompt: "Enter the Java binary software path location:"
  roles:
    - db2-java
