---
- name: Java Pre-Check on Database server
  hosts: ebisddb01.abcbs.net
  gather_facts: no
  tasks:
    - name: Find all path where Java is Installed
      shell: |
        find / -type f -name "java" -executable 2>/dev/null
      register: java_paths
      ignore_errors: yes
      changed_when: false

    - name: Ensure Java path are uniqe
      set_fact:
        unique_java_paths: "{{ java_paths.stdout_lines | unique }}"

    - name: Display found Java paths
      debug:
        msg: "Found Java binary at : {{ item }}"
      with_items: "{{ unique_java_paths}}"
      when: unique_java_paths | length > 0

    - name: Check Java Version for each path 
      shell: |
        {{ item }} -version 2 > $1
      with_items: "{{ unique_java_paths }}"
      register: java_versions
      ignore_errors: yes
      changed_when: false 

    - name: Display Java version result
      debug: 
        msg: | 
          Path: {{ item.item }}
          Version Output: |
            {{ item.stdout default ('No output') }}
            Errors (if any): {{ item.stderr | default('No errors') }}
      with_items: "{{ java_versions.results}}" 
      when: java_versions.results | length > 0
        
    - name:  Fail if no java binarires are found
      fail:
        msg: "No Java binaries were found on the server"
      when: unique_java_paths |length == 0
