---
- name: Stop Start  DB2 
  hosts: ebissdb01.abcbs.net
  become: yes
  become_method: sudo
  gather_facts: True 
  vars_prompt:
    - name: db2_database
      prompt: "Enter Database name:"
    - name: db2_action
      prompt: "Enter action(start/stop):"
  tasks:
    - name: Check DB2 status
      shell: db2 list active databases
      register: db2_status
    - name: Stop DB2
      shell: sudo -iu {{db2_database}} db2stop force
      when: db2_action == "stop"
    - name: Start DB2
      shell: sudo -iu {{db2_database}} db2start
      when: db2_action == "start"
