---
- name: Update DB2 SSL Certificate 
  gather_facts: true
  hosts:  all
  become: yes
  become_method: sudo
  vars:
    cert_source: "/tmp/cert/"
  vars_prompt:
    - name: cert_source
      prompt: "Enter the ssl certificate  path location:"
  roles:
    - db2-ssl 
