---
- name: Update DB2 SSL Certificate 
  gather_facts: true
  hosts:  all
  become: yes
  become_method: sudo
  vars:
    cert_name: "{{ cert_name | default ('',true)}}"
    # User need to pass certificate name
  roles:
    - db2-ssl 
