---  

- name: Extract IBM DB2 package
  ansible.builtin.command:
    cmd: "tar -xvzf {{ db2_bin_temp }}/special_43682_v11.5.9_linuxx64_universal_fixpack.tar.gz -C {{db2_binary_location}}"

- name: Get running DB2 databses instance
  shell: ps -ef|grep -w db2sysc|grep -v grep|awk '{print $1}'|sort|uniq
  register: running_instances

- name: Get fence ID for each instance
  shell:
    cmd: ". ~/.bash_profile;db2pd -fmp 2>/dev/null |grep -w User |awk '{print $3}'|sort|uniq"
  register: fence_ids
  with_items: "{{ running_instances.stdout_lines }}"
  loop_control:
    loop_var: item
  become_user: igidb2

    
- name: Debug fence_ids raw output
  debug:
    var: fence_ids.results
  
- name: Extract fence_ids
  debug:
    msg: "Fenced user for Instance {{ item.item }}: {{ item.stdout | default('No output') }}"
  with_items: "{{ fence_ids.results }}"
  loop_control:
    loop_var: item

- name: debug and extract fence id
  debug:
    msg: "Fenced user for Instance {{ item.item }}: {{ fence_ids.results[db2_index].stdout | default('No output') }}"
  with_items: "{{ fence_ids.results }}"
  loop_control:
    loop_var: item
    index_var: db2_index

    
- name: Stop each db2 database
  become_user: igidb2
  shell:
    cmd: ". ~/.bash_profile;db2stop force"
  loop: "{{ running_instances.stdout.split() }}"
  loop_control:
    index_var: instance
  
- name: create  directory for new installation
  ansible.builtin.file:
    path:  "{{ new_db2_path }}"
    state: directory
    mode: '0775'

    
- name: Run db2iupdt for each instance
  shell: |
    ./db2iupdt -u {{ fence_ids }} {{ instance }}
  args:
    chdir: "{{  new_db2_path }}/instance"
  loop: "{{ running_instances.stdout_lines }}"
  loop_control:
    loop_var: instance
    index_var: db2_index
  vars:
    fence_id: " {{ fence_ids.results[db2_index].stdout |trim }}"


  
- name: Start each db2 database
  become_user: igidb2
  shell:
    cmd: ". ~/.bash_profile;db2start" 
  loop: "{{ running_instances.stdout.split() }}"
  loop_control:
    loop_var: instance
  


