---  
- name: Get running DB2 databses instance
  shell: ps -ef|grep -w db2sysc|grep -v grep|awk '{print $1}'|sort|uniq
  register: running_instances

- name: Get fence ID for each instance
  shell: sudo -iu igidb2 db2pd -fmp |grep -w User | awk '{print $3}'|sort|uniq
  register: fence_ids
  with_items: "{{ running_instances.stdout_lines }}"
  loop_control:
    loop_var: item
    
- name: Debug fence_ids raw output
  debug:
    var: fence_ids.results
  
- name: Extract fence_ids
  debug:
    msg: "Fenced user for Instance {{ item.item }}: {{ item.stdout }}"
  with_items: "{{ fence_ids.results }}"
  loop_control:
    loop_var: item


