---
- name: Print system hostname
  command: hostname
  become: yes
  become_method: sudo
  
- name: Get running DB2 databses instance
  shell: ps -ef|grep -w db2sysc|grep -v grep|awk '{print $1}'|sort|uniq
  register: running_instances

- name: Get fence ID for each instance
  shell: |
    sudo -iu {{item}}  db2pd -fmp |grep -i "Fenced user" | awk '{print $3}'
  register: fence_ids
  with_items: "{{ running_instances.stdout_lines }}"
  loop_control: 
    loop_var: instance

- name: Run db2support and rename the file
  shell: |
    sudo -iu {{item}} db2support {{ temp_dir }} -s
    mv {{ temp_dir }}/db2support.zip {{ temp_dir }}/db2support_{{instance}}.zip
    with_items: "{{ running_instances.stdout_lines }}"
    loop_control:
      loop_var: instance
      
- name: Stop each db2 database
  debug:
    msg: "Stopping DB2 database: {{ item }}"
  loop: "{{ running_instances.stdout.split() }}"
  loop_control:
    index_var: db2_instance
  check_mode: no
    
- name: Stop each db2 database
  shell: sudo -iu {{item}} db2stop force
  loop: "{{ running_instances.stdout.split() }}"
  loop_control:
    index_var: db2_instance 
  
- name: create  directory for new installation
  ansible.builtin.file:
    path:  "{{ new_db2_path }}"
    state: directory
    mode: '0775'
    
- name: Run the install special build fix pack
  shell: |
    ./installFixPack -b {{ base_db2_path }} -n -y -p {{ new_db2_path }}
  args:
    chdir: "{{ base_db2_path }}"
    
- name: Run db2iupdt for each instance
  shell: |
    /opt/ibm/db2/V11.5.9_SP/instance/db2iupdt -u {{ item.fence_id }} {{ item.instance }}
  with_items: "{{ running_instances.stdout_lines }}"
  loop_control:
    loop_var: instance
    vars:
      fence_id: " {{ fence_ids.results[loop.index - 1].stdout.strip() }}"



- name: Start each db2 database
  debug:
    msg: "Starting DB2 database: {{ item }}"
  loop: "{{ - name: Stop each db2 database
  debug:
    msg: "Stopping DB2 database: {{ item }}"
  loop: "{{ running_instances.stdout.split() }}"
  loop_control:
    index_var: db2_instance
  check_mode: no
    
- name: Start each db2 database
  shell: sudo -iu {{item}} db2start
  loop: "{{ - name: Stop each db2 database
  debug:
    msg: "Stopping DB2 database: {{ item }}"
  loop: "{{ running_instances.stdout.split() }}"
  loop_control:
    index_var: db2_instance
  check_mode: no
    
 

    
