---
- name: Print system hostname
  command: hostname
  become: yes
  become_method: sudo
  
- name: Stop database bcuaixp
  shell: sudo -iu bcuaixp db2stop force
  register: stop result
- name: Check id database stopped 
  failed_when: stop_result.rc !=0
  debug:
    msg: "failed to stop database"
    
- name: Stop database ebihost
  shell: sudo -iu ebihost db2stop force
  register: stop result
- name: Check id database stopped 
  failed_when: stop_result.rc !=0
  debug:
    msg: "failed to stop database"
    
- name: Stop database ebiedw
  shell: sudo -iu ebiedw db2stop force
  register: stop result
- name: Check id database stopped 
  failed_when: stop_result.rc !=0
  debug:
    msg: "failed to stop database"

- name: Extract IBM Java package
  ansible.builtin.command:
    cmd: tar -xvzf /db2audit/java/ibm-java-sdk-8.0-8.30-linux-x86_64.tgz -C /db2audit/java/java64

- name: Rename IBM Java package
  ansible.builtin.command:
    cmd: mv /db2audit/java/java64/ibm-java-x86_64-80 /db2audit/java/java64/jdk64

- name: change owner IBM Java package
  ansible.builtin.file:
    path: /db2audit/java/java64/jdk64
    owner: bin
    group: bin
    recurse: yes
- name: Start database
  shell: sudo -iu bcuaixp db2start
  changed_when: stop_result.changed
- name: Start database
  shell: sudo -iu ebihost db2start
  changed_when: stop_result.changed
    
