---
- name: Print system hostname
  command: hostname
- name: Extract IBM Java package
  ansible.builtin.unarchive:
    src: /db2audit/java/ibm-java-sdk-8.0-8.30-linux-x86_64.tgz
    dest: /db2audit/java/java64
