---
- name: Print system hostname
  command: hostname
  become: yes
  become_method: sudo

- name: Extract IBM Java package
  ansible.builtin.command:
    cmd: tar -xvzf /db2audit/java/ibm-java-sdk-8.0-8.30-linux-x86_64.tgz -C /db2audit/java/java64
    
- name: taking backup of alraedy installed IBM Java package
  ansible.builtin.command:
    cmd: mv /opt/ibm/db2/V11.5.9/java/jdk64  /db2audit/java/jdk64_09172024 

- name: Rename IBM Java package
  ansible.builtin.command:
    cmd: mv /db2audit/java/java64/ibm-java-x86_64-80 /db2audit/java/java64/jdk64
    
- name: copy IBM Java package
  ansible.builtin.command:
    cmd: mv /db2audit/java/java64/jdk64 /opt/ibm/db2/V11.5.9/java/
    
- name: change owner IBM Java package
  ansible.builtin.file:
    path: /opt/ibm/db2/V11.5.9/java/jdk64
    owner: bin
    group: bin
    recurse: yes
    
- name: Start database
  shell: sudo -iu bcuaixp db2start

  
- name: Start database
  shell: sudo -iu ebihost db2start

  
- name: Start database
  shell: sudo -iu ebiedw db2start

    
